// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	user "backend/api/internal/handler/user"
	vip "backend/api/internal/handler/vip"
	"backend/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/user/:user_id",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/:user_id",
				Handler: user.UpdateUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/user/:user_id",
				Handler: user.DeleteUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/:user_id/detail",
				Handler: user.GetUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/:user_id/password",
				Handler: user.UpdateUserPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/:user_id/vip",
				Handler: user.UpdateUserVipHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/:user_id/vip",
				Handler: user.GetUserVipStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/:user_id/vip/active",
				Handler: user.GetUserActiveVipRecordHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/:user_id/vip/auto-renew",
				Handler: user.UpdateAutoRenewHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/:user_id/vip/check",
				Handler: user.CheckUserVipHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/:user_id/vip/orders",
				Handler: user.GetVipOrdersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/:user_id/vip/orders",
				Handler: user.CreateVipOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/:user_id/vip/records",
				Handler: user.GetVipHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/:user_id/vip/sync",
				Handler: user.SyncUserVipStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/users",
				Handler: user.GetUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/users/count",
				Handler: user.GetUserCountHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/vip/plans",
				Handler: vip.GetVipPlansHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/vip/plans",
				Handler: vip.CreateVipPlanHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/vip/plans/:plan_id",
				Handler: vip.GetVipPlanHandler(serverCtx),
			},
		},
	)
}
