// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: super.proto

package super

import (
	"context"

	"backend/rpc/pb/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseResp              = rpc.BaseResp
	CheckUserVipReq       = rpc.CheckUserVipReq
	CheckUserVipResp      = rpc.CheckUserVipResp
	CreateVipOrderReq     = rpc.CreateVipOrderReq
	CreateVipOrderResp    = rpc.CreateVipOrderResp
	GetUserCountReq       = rpc.GetUserCountReq
	GetUserCountResp      = rpc.GetUserCountResp
	GetUserInfoReq        = rpc.GetUserInfoReq
	GetUserInfoResp       = rpc.GetUserInfoResp
	GetUserVipStatusReq   = rpc.GetUserVipStatusReq
	GetUserVipStatusResp  = rpc.GetUserVipStatusResp
	GetUsersReq           = rpc.GetUsersReq
	GetUsersResp          = rpc.GetUsersResp
	GetVipOrdersReq       = rpc.GetVipOrdersReq
	GetVipOrdersResp      = rpc.GetVipOrdersResp
	GetVipPlansReq        = rpc.GetVipPlansReq
	GetVipPlansResp       = rpc.GetVipPlansResp
	GetVipRecordsReq      = rpc.GetVipRecordsReq
	GetVipRecordsResp     = rpc.GetVipRecordsResp
	SyncUserVipStatusReq  = rpc.SyncUserVipStatusReq
	SyncUserVipStatusResp = rpc.SyncUserVipStatusResp
	UpdateAutoRenewReq    = rpc.UpdateAutoRenewReq
	UpdateAutoRenewResp   = rpc.UpdateAutoRenewResp
	User                  = rpc.User
	VipOrder              = rpc.VipOrder
	VipPlan               = rpc.VipPlan
	VipRecord             = rpc.VipRecord

	Super interface {
		// 用户相关服务
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		GetUsers(ctx context.Context, in *GetUsersReq, opts ...grpc.CallOption) (*GetUsersResp, error)
		GetUserCount(ctx context.Context, in *GetUserCountReq, opts ...grpc.CallOption) (*GetUserCountResp, error)
		// VIP套餐相关服务
		GetVipPlans(ctx context.Context, in *GetVipPlansReq, opts ...grpc.CallOption) (*GetVipPlansResp, error)
		// VIP订单相关服务
		CreateVipOrder(ctx context.Context, in *CreateVipOrderReq, opts ...grpc.CallOption) (*CreateVipOrderResp, error)
		GetVipOrders(ctx context.Context, in *GetVipOrdersReq, opts ...grpc.CallOption) (*GetVipOrdersResp, error)
		// VIP记录相关服务
		GetVipRecords(ctx context.Context, in *GetVipRecordsReq, opts ...grpc.CallOption) (*GetVipRecordsResp, error)
		// VIP状态相关服务
		GetUserVipStatus(ctx context.Context, in *GetUserVipStatusReq, opts ...grpc.CallOption) (*GetUserVipStatusResp, error)
		CheckUserVip(ctx context.Context, in *CheckUserVipReq, opts ...grpc.CallOption) (*CheckUserVipResp, error)
		UpdateAutoRenew(ctx context.Context, in *UpdateAutoRenewReq, opts ...grpc.CallOption) (*UpdateAutoRenewResp, error)
		SyncUserVipStatus(ctx context.Context, in *SyncUserVipStatusReq, opts ...grpc.CallOption) (*SyncUserVipStatusResp, error)
	}

	defaultSuper struct {
		cli zrpc.Client
	}
)

func NewSuper(cli zrpc.Client) Super {
	return &defaultSuper{
		cli: cli,
	}
}

// 用户相关服务
func (m *defaultSuper) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultSuper) GetUsers(ctx context.Context, in *GetUsersReq, opts ...grpc.CallOption) (*GetUsersResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.GetUsers(ctx, in, opts...)
}

func (m *defaultSuper) GetUserCount(ctx context.Context, in *GetUserCountReq, opts ...grpc.CallOption) (*GetUserCountResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.GetUserCount(ctx, in, opts...)
}

// VIP套餐相关服务
func (m *defaultSuper) GetVipPlans(ctx context.Context, in *GetVipPlansReq, opts ...grpc.CallOption) (*GetVipPlansResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.GetVipPlans(ctx, in, opts...)
}

// VIP订单相关服务
func (m *defaultSuper) CreateVipOrder(ctx context.Context, in *CreateVipOrderReq, opts ...grpc.CallOption) (*CreateVipOrderResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.CreateVipOrder(ctx, in, opts...)
}

func (m *defaultSuper) GetVipOrders(ctx context.Context, in *GetVipOrdersReq, opts ...grpc.CallOption) (*GetVipOrdersResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.GetVipOrders(ctx, in, opts...)
}

// VIP记录相关服务
func (m *defaultSuper) GetVipRecords(ctx context.Context, in *GetVipRecordsReq, opts ...grpc.CallOption) (*GetVipRecordsResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.GetVipRecords(ctx, in, opts...)
}

// VIP状态相关服务
func (m *defaultSuper) GetUserVipStatus(ctx context.Context, in *GetUserVipStatusReq, opts ...grpc.CallOption) (*GetUserVipStatusResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.GetUserVipStatus(ctx, in, opts...)
}

func (m *defaultSuper) CheckUserVip(ctx context.Context, in *CheckUserVipReq, opts ...grpc.CallOption) (*CheckUserVipResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.CheckUserVip(ctx, in, opts...)
}

func (m *defaultSuper) UpdateAutoRenew(ctx context.Context, in *UpdateAutoRenewReq, opts ...grpc.CallOption) (*UpdateAutoRenewResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.UpdateAutoRenew(ctx, in, opts...)
}

func (m *defaultSuper) SyncUserVipStatus(ctx context.Context, in *SyncUserVipStatusReq, opts ...grpc.CallOption) (*SyncUserVipStatusResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.SyncUserVipStatus(ctx, in, opts...)
}
