// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: super.proto

package super

import (
	"context"

	"backend/rpc/pb/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckUserVipReq            = rpc.CheckUserVipReq
	CheckUserVipResp           = rpc.CheckUserVipResp
	CreateVipOrderReq          = rpc.CreateVipOrderReq
	CreateVipOrderResp         = rpc.CreateVipOrderResp
	CreateVipPlanReq           = rpc.CreateVipPlanReq
	CreateVipPlanResp          = rpc.CreateVipPlanResp
	DeleteUserReq              = rpc.DeleteUserReq
	DeleteUserResp             = rpc.DeleteUserResp
	GetUserActiveVipRecordReq  = rpc.GetUserActiveVipRecordReq
	GetUserActiveVipRecordResp = rpc.GetUserActiveVipRecordResp
	GetUserCountReq            = rpc.GetUserCountReq
	GetUserCountResp           = rpc.GetUserCountResp
	GetUserInfoReq             = rpc.GetUserInfoReq
	GetUserInfoResp            = rpc.GetUserInfoResp
	GetUserReq                 = rpc.GetUserReq
	GetUserResp                = rpc.GetUserResp
	GetUserVipStatusReq        = rpc.GetUserVipStatusReq
	GetUserVipStatusResp       = rpc.GetUserVipStatusResp
	GetUsersReq                = rpc.GetUsersReq
	GetUsersResp               = rpc.GetUsersResp
	GetVipOrdersReq            = rpc.GetVipOrdersReq
	GetVipOrdersResp           = rpc.GetVipOrdersResp
	GetVipPlanReq              = rpc.GetVipPlanReq
	GetVipPlanResp             = rpc.GetVipPlanResp
	GetVipPlansReq             = rpc.GetVipPlansReq
	GetVipPlansResp            = rpc.GetVipPlansResp
	GetVipRecordsReq           = rpc.GetVipRecordsReq
	GetVipRecordsResp          = rpc.GetVipRecordsResp
	LoginReq                   = rpc.LoginReq
	LoginResp                  = rpc.LoginResp
	RegisterReq                = rpc.RegisterReq
	RegisterResp               = rpc.RegisterResp
	SyncUserVipStatusReq       = rpc.SyncUserVipStatusReq
	SyncUserVipStatusResp      = rpc.SyncUserVipStatusResp
	UpdateAutoRenewReq         = rpc.UpdateAutoRenewReq
	UpdateAutoRenewResp        = rpc.UpdateAutoRenewResp
	UpdateUserInfoReq          = rpc.UpdateUserInfoReq
	UpdateUserInfoResp         = rpc.UpdateUserInfoResp
	UpdateUserPasswordReq      = rpc.UpdateUserPasswordReq
	UpdateUserPasswordResp     = rpc.UpdateUserPasswordResp
	UpdateUserVipReq           = rpc.UpdateUserVipReq
	UpdateUserVipResp          = rpc.UpdateUserVipResp
	User                       = rpc.User
	VipOrder                   = rpc.VipOrder
	VipPlan                    = rpc.VipPlan
	VipRecord                  = rpc.VipRecord

	Super interface {
		// 用户相关服务
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
		UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error)
		UpdateUserPassword(ctx context.Context, in *UpdateUserPasswordReq, opts ...grpc.CallOption) (*UpdateUserPasswordResp, error)
		DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResp, error)
		UpdateUserVip(ctx context.Context, in *UpdateUserVipReq, opts ...grpc.CallOption) (*UpdateUserVipResp, error)
		GetUsers(ctx context.Context, in *GetUsersReq, opts ...grpc.CallOption) (*GetUsersResp, error)
		GetUserCount(ctx context.Context, in *GetUserCountReq, opts ...grpc.CallOption) (*GetUserCountResp, error)
		// VIP套餐相关服务
		GetVipPlans(ctx context.Context, in *GetVipPlansReq, opts ...grpc.CallOption) (*GetVipPlansResp, error)
		GetVipPlan(ctx context.Context, in *GetVipPlanReq, opts ...grpc.CallOption) (*GetVipPlanResp, error)
		CreateVipPlan(ctx context.Context, in *CreateVipPlanReq, opts ...grpc.CallOption) (*CreateVipPlanResp, error)
		// VIP订单相关服务
		CreateVipOrder(ctx context.Context, in *CreateVipOrderReq, opts ...grpc.CallOption) (*CreateVipOrderResp, error)
		GetVipOrders(ctx context.Context, in *GetVipOrdersReq, opts ...grpc.CallOption) (*GetVipOrdersResp, error)
		// VIP记录相关服务
		GetVipRecords(ctx context.Context, in *GetVipRecordsReq, opts ...grpc.CallOption) (*GetVipRecordsResp, error)
		GetUserActiveVipRecord(ctx context.Context, in *GetUserActiveVipRecordReq, opts ...grpc.CallOption) (*GetUserActiveVipRecordResp, error)
		// VIP状态相关服务
		GetUserVipStatus(ctx context.Context, in *GetUserVipStatusReq, opts ...grpc.CallOption) (*GetUserVipStatusResp, error)
		CheckUserVip(ctx context.Context, in *CheckUserVipReq, opts ...grpc.CallOption) (*CheckUserVipResp, error)
		UpdateAutoRenew(ctx context.Context, in *UpdateAutoRenewReq, opts ...grpc.CallOption) (*UpdateAutoRenewResp, error)
		SyncUserVipStatus(ctx context.Context, in *SyncUserVipStatusReq, opts ...grpc.CallOption) (*SyncUserVipStatusResp, error)
	}

	defaultSuper struct {
		cli zrpc.Client
	}
)

func NewSuper(cli zrpc.Client) Super {
	return &defaultSuper{
		cli: cli,
	}
}

// 用户相关服务
func (m *defaultSuper) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultSuper) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultSuper) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultSuper) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultSuper) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}

func (m *defaultSuper) UpdateUserPassword(ctx context.Context, in *UpdateUserPasswordReq, opts ...grpc.CallOption) (*UpdateUserPasswordResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.UpdateUserPassword(ctx, in, opts...)
}

func (m *defaultSuper) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}

func (m *defaultSuper) UpdateUserVip(ctx context.Context, in *UpdateUserVipReq, opts ...grpc.CallOption) (*UpdateUserVipResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.UpdateUserVip(ctx, in, opts...)
}

func (m *defaultSuper) GetUsers(ctx context.Context, in *GetUsersReq, opts ...grpc.CallOption) (*GetUsersResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.GetUsers(ctx, in, opts...)
}

func (m *defaultSuper) GetUserCount(ctx context.Context, in *GetUserCountReq, opts ...grpc.CallOption) (*GetUserCountResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.GetUserCount(ctx, in, opts...)
}

// VIP套餐相关服务
func (m *defaultSuper) GetVipPlans(ctx context.Context, in *GetVipPlansReq, opts ...grpc.CallOption) (*GetVipPlansResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.GetVipPlans(ctx, in, opts...)
}

func (m *defaultSuper) GetVipPlan(ctx context.Context, in *GetVipPlanReq, opts ...grpc.CallOption) (*GetVipPlanResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.GetVipPlan(ctx, in, opts...)
}

func (m *defaultSuper) CreateVipPlan(ctx context.Context, in *CreateVipPlanReq, opts ...grpc.CallOption) (*CreateVipPlanResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.CreateVipPlan(ctx, in, opts...)
}

// VIP订单相关服务
func (m *defaultSuper) CreateVipOrder(ctx context.Context, in *CreateVipOrderReq, opts ...grpc.CallOption) (*CreateVipOrderResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.CreateVipOrder(ctx, in, opts...)
}

func (m *defaultSuper) GetVipOrders(ctx context.Context, in *GetVipOrdersReq, opts ...grpc.CallOption) (*GetVipOrdersResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.GetVipOrders(ctx, in, opts...)
}

// VIP记录相关服务
func (m *defaultSuper) GetVipRecords(ctx context.Context, in *GetVipRecordsReq, opts ...grpc.CallOption) (*GetVipRecordsResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.GetVipRecords(ctx, in, opts...)
}

func (m *defaultSuper) GetUserActiveVipRecord(ctx context.Context, in *GetUserActiveVipRecordReq, opts ...grpc.CallOption) (*GetUserActiveVipRecordResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.GetUserActiveVipRecord(ctx, in, opts...)
}

// VIP状态相关服务
func (m *defaultSuper) GetUserVipStatus(ctx context.Context, in *GetUserVipStatusReq, opts ...grpc.CallOption) (*GetUserVipStatusResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.GetUserVipStatus(ctx, in, opts...)
}

func (m *defaultSuper) CheckUserVip(ctx context.Context, in *CheckUserVipReq, opts ...grpc.CallOption) (*CheckUserVipResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.CheckUserVip(ctx, in, opts...)
}

func (m *defaultSuper) UpdateAutoRenew(ctx context.Context, in *UpdateAutoRenewReq, opts ...grpc.CallOption) (*UpdateAutoRenewResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.UpdateAutoRenew(ctx, in, opts...)
}

func (m *defaultSuper) SyncUserVipStatus(ctx context.Context, in *SyncUserVipStatusReq, opts ...grpc.CallOption) (*SyncUserVipStatusResp, error) {
	client := rpc.NewSuperClient(m.cli.Conn())
	return client.SyncUserVipStatus(ctx, in, opts...)
}
