// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: super.proto

package server

import (
	"context"

	"backend/rpc/internal/logic"
	"backend/rpc/internal/svc"
	"backend/rpc/pb/rpc"
)

type SuperServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedSuperServer
}

func NewSuperServer(svcCtx *svc.ServiceContext) *SuperServer {
	return &SuperServer{
		svcCtx: svcCtx,
	}
}

// 用户相关服务
func (s *SuperServer) GetUserInfo(ctx context.Context, in *rpc.GetUserInfoReq) (*rpc.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *SuperServer) GetUsers(ctx context.Context, in *rpc.GetUsersReq) (*rpc.GetUsersResp, error) {
	l := logic.NewGetUsersLogic(ctx, s.svcCtx)
	return l.GetUsers(in)
}

func (s *SuperServer) GetUserCount(ctx context.Context, in *rpc.GetUserCountReq) (*rpc.GetUserCountResp, error) {
	l := logic.NewGetUserCountLogic(ctx, s.svcCtx)
	return l.GetUserCount(in)
}

// VIP套餐相关服务
func (s *SuperServer) GetVipPlans(ctx context.Context, in *rpc.GetVipPlansReq) (*rpc.GetVipPlansResp, error) {
	l := logic.NewGetVipPlansLogic(ctx, s.svcCtx)
	return l.GetVipPlans(in)
}

// VIP订单相关服务
func (s *SuperServer) CreateVipOrder(ctx context.Context, in *rpc.CreateVipOrderReq) (*rpc.CreateVipOrderResp, error) {
	l := logic.NewCreateVipOrderLogic(ctx, s.svcCtx)
	return l.CreateVipOrder(in)
}

func (s *SuperServer) GetVipOrders(ctx context.Context, in *rpc.GetVipOrdersReq) (*rpc.GetVipOrdersResp, error) {
	l := logic.NewGetVipOrdersLogic(ctx, s.svcCtx)
	return l.GetVipOrders(in)
}

// VIP记录相关服务
func (s *SuperServer) GetVipRecords(ctx context.Context, in *rpc.GetVipRecordsReq) (*rpc.GetVipRecordsResp, error) {
	l := logic.NewGetVipRecordsLogic(ctx, s.svcCtx)
	return l.GetVipRecords(in)
}

// VIP状态相关服务
func (s *SuperServer) GetUserVipStatus(ctx context.Context, in *rpc.GetUserVipStatusReq) (*rpc.GetUserVipStatusResp, error) {
	l := logic.NewGetUserVipStatusLogic(ctx, s.svcCtx)
	return l.GetUserVipStatus(in)
}

func (s *SuperServer) CheckUserVip(ctx context.Context, in *rpc.CheckUserVipReq) (*rpc.CheckUserVipResp, error) {
	l := logic.NewCheckUserVipLogic(ctx, s.svcCtx)
	return l.CheckUserVip(in)
}

func (s *SuperServer) UpdateAutoRenew(ctx context.Context, in *rpc.UpdateAutoRenewReq) (*rpc.UpdateAutoRenewResp, error) {
	l := logic.NewUpdateAutoRenewLogic(ctx, s.svcCtx)
	return l.UpdateAutoRenew(in)
}

func (s *SuperServer) SyncUserVipStatus(ctx context.Context, in *rpc.SyncUserVipStatusReq) (*rpc.SyncUserVipStatusResp, error) {
	l := logic.NewSyncUserVipStatusLogic(ctx, s.svcCtx)
	return l.SyncUserVipStatus(in)
}
