// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: superservice.proto

package server

import (
	"context"

	"backend/rpc/internal/logic"
	"backend/rpc/internal/svc"
	"backend/rpc/pb/super"
)

type SuperServer struct {
	svcCtx *svc.ServiceContext
	super.UnimplementedSuperServer
}

func NewSuperServer(svcCtx *svc.ServiceContext) *SuperServer {
	return &SuperServer{
		svcCtx: svcCtx,
	}
}

// 用户相关服务
func (s *SuperServer) Register(ctx context.Context, in *super.RegisterReq) (*super.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *SuperServer) Login(ctx context.Context, in *super.LoginReq) (*super.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *SuperServer) GetUserInfo(ctx context.Context, in *super.GetUserInfoReq) (*super.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *SuperServer) GetUser(ctx context.Context, in *super.GetUserReq) (*super.GetUserResp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *SuperServer) UpdateUserInfo(ctx context.Context, in *super.UpdateUserInfoReq) (*super.UpdateUserInfoResp, error) {
	l := logic.NewUpdateUserInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserInfo(in)
}

func (s *SuperServer) UpdateUserPassword(ctx context.Context, in *super.UpdateUserPasswordReq) (*super.UpdateUserPasswordResp, error) {
	l := logic.NewUpdateUserPasswordLogic(ctx, s.svcCtx)
	return l.UpdateUserPassword(in)
}

func (s *SuperServer) DeleteUser(ctx context.Context, in *super.DeleteUserReq) (*super.DeleteUserResp, error) {
	l := logic.NewDeleteUserLogic(ctx, s.svcCtx)
	return l.DeleteUser(in)
}

func (s *SuperServer) UpdateUserVip(ctx context.Context, in *super.UpdateUserVipReq) (*super.UpdateUserVipResp, error) {
	l := logic.NewUpdateUserVipLogic(ctx, s.svcCtx)
	return l.UpdateUserVip(in)
}

func (s *SuperServer) GetUsers(ctx context.Context, in *super.GetUsersReq) (*super.GetUsersResp, error) {
	l := logic.NewGetUsersLogic(ctx, s.svcCtx)
	return l.GetUsers(in)
}

func (s *SuperServer) GetUserCount(ctx context.Context, in *super.GetUserCountReq) (*super.GetUserCountResp, error) {
	l := logic.NewGetUserCountLogic(ctx, s.svcCtx)
	return l.GetUserCount(in)
}

// VIP套餐相关服务
func (s *SuperServer) GetVipPlans(ctx context.Context, in *super.GetVipPlansReq) (*super.GetVipPlansResp, error) {
	l := logic.NewGetVipPlansLogic(ctx, s.svcCtx)
	return l.GetVipPlans(in)
}

func (s *SuperServer) GetVipPlan(ctx context.Context, in *super.GetVipPlanReq) (*super.GetVipPlanResp, error) {
	l := logic.NewGetVipPlanLogic(ctx, s.svcCtx)
	return l.GetVipPlan(in)
}

func (s *SuperServer) CreateVipPlan(ctx context.Context, in *super.CreateVipPlanReq) (*super.CreateVipPlanResp, error) {
	l := logic.NewCreateVipPlanLogic(ctx, s.svcCtx)
	return l.CreateVipPlan(in)
}

// VIP订单相关服务
func (s *SuperServer) CreateVipOrder(ctx context.Context, in *super.CreateVipOrderReq) (*super.CreateVipOrderResp, error) {
	l := logic.NewCreateVipOrderLogic(ctx, s.svcCtx)
	return l.CreateVipOrder(in)
}

func (s *SuperServer) GetVipOrders(ctx context.Context, in *super.GetVipOrdersReq) (*super.GetVipOrdersResp, error) {
	l := logic.NewGetVipOrdersLogic(ctx, s.svcCtx)
	return l.GetVipOrders(in)
}

// VIP记录相关服务
func (s *SuperServer) GetVipRecords(ctx context.Context, in *super.GetVipRecordsReq) (*super.GetVipRecordsResp, error) {
	l := logic.NewGetVipRecordsLogic(ctx, s.svcCtx)
	return l.GetVipRecords(in)
}

func (s *SuperServer) GetUserActiveVipRecord(ctx context.Context, in *super.GetUserActiveVipRecordReq) (*super.GetUserActiveVipRecordResp, error) {
	l := logic.NewGetUserActiveVipRecordLogic(ctx, s.svcCtx)
	return l.GetUserActiveVipRecord(in)
}

// VIP状态相关服务
func (s *SuperServer) GetUserVipStatus(ctx context.Context, in *super.GetUserVipStatusReq) (*super.GetUserVipStatusResp, error) {
	l := logic.NewGetUserVipStatusLogic(ctx, s.svcCtx)
	return l.GetUserVipStatus(in)
}

func (s *SuperServer) CheckUserVip(ctx context.Context, in *super.CheckUserVipReq) (*super.CheckUserVipResp, error) {
	l := logic.NewCheckUserVipLogic(ctx, s.svcCtx)
	return l.CheckUserVip(in)
}

func (s *SuperServer) UpdateAutoRenew(ctx context.Context, in *super.UpdateAutoRenewReq) (*super.UpdateAutoRenewResp, error) {
	l := logic.NewUpdateAutoRenewLogic(ctx, s.svcCtx)
	return l.UpdateAutoRenew(in)
}

func (s *SuperServer) SyncUserVipStatus(ctx context.Context, in *super.SyncUserVipStatusReq) (*super.SyncUserVipStatusResp, error) {
	l := logic.NewSyncUserVipStatusLogic(ctx, s.svcCtx)
	return l.SyncUserVipStatus(in)
}

// AI使用量相关服务
func (s *SuperServer) GetAIUsage(ctx context.Context, in *super.GetAIUsageReq) (*super.GetAIUsageResp, error) {
	l := logic.NewGetAIUsageLogic(ctx, s.svcCtx)
	return l.GetAIUsage(in)
}

func (s *SuperServer) UpdateAIUsage(ctx context.Context, in *super.UpdateAIUsageReq) (*super.UpdateAIUsageResp, error) {
	l := logic.NewUpdateAIUsageLogic(ctx, s.svcCtx)
	return l.UpdateAIUsage(in)
}
