// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AIRequestReq struct {
	Prompt string `json:"prompt"`
}

type AIRequestResp struct {
	BaseResp
	Data AIResponseData `json:"data"`
}

type AIResponseData struct {
	Response string      `json:"response"`
	Usage    AIUsageData `json:"usage"`
}

type AIUsageData struct {
	IsVip           bool   `json:"is_vip"`
	AIChatCount     int    `json:"ai_chat_count"`
	AIChatLimit     int    `json:"ai_chat_limit"`
	AIContentCount  int    `json:"ai_content_count"`
	AIContentLimit  int    `json:"ai_content_limit"`
	AIAnalysisCount int    `json:"ai_analysis_count"`
	AIAnalysisLimit int    `json:"ai_analysis_limit"`
	AILastResetAt   string `json:"ai_last_reset_at"`
}

type BaseResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Success bool   `json:"success"`
}

type CheckUserVipReq struct {
	UserId string `path:"user_id"`
}

type CheckUserVipResp struct {
	BaseResp
	Data bool `json:"data"`
}

type CreateVipOrderReq struct {
	UserId string `path:"user_id"`
	PlanId string `json:"plan_id"`
}

type CreateVipOrderResp struct {
	BaseResp
	Data VipOrder `json:"data"`
}

type CreateVipPlanReq struct {
	Name         string  `json:"name"`
	Description  string  `json:"description"`
	Price        float64 `json:"price"`
	DurationDays int     `json:"duration_days"`
}

type CreateVipPlanResp struct {
	BaseResp
	Data VipPlan `json:"data"`
}

type DeleteUserReq struct {
	UserId string `path:"user_id"`
}

type DeleteUserResp struct {
	BaseResp
}

type EmptyReq struct {
}

type EmptyResp struct {
}

type GetAIUsageResp struct {
	BaseResp
	Data AIUsageData `json:"data"`
}

type GetUserActiveVipRecordReq struct {
	UserId string `path:"user_id"`
}

type GetUserActiveVipRecordResp struct {
	BaseResp
	Data VipRecord `json:"data"`
}

type GetUserCountResp struct {
	BaseResp
	Data int `json:"data"`
}

type GetUserInfoReq struct {
	UserId string `path:"user_id"`
}

type GetUserInfoResp struct {
	BaseResp
	Data User `json:"data"`
}

type GetUserReq struct {
	UserId string `path:"user_id"`
}

type GetUserResp struct {
	BaseResp
	Data User `json:"data"`
}

type GetUserVipStatusResp struct {
	BaseResp
	Data UserVipStatusData `json:"data"`
}

type GetUsersReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=10"`
}

type GetUsersResp struct {
	BaseResp
	Data  []User `json:"data"`
	Total int    `json:"total"`
}

type GetVipHistoryReq struct {
	UserId   string `path:"user_id"`
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=10"`
}

type GetVipHistoryResp struct {
	BaseResp
	Data  []VipRecord `json:"data"`
	Total int         `json:"total"`
}

type GetVipOrdersReq struct {
	UserId   string `path:"user_id"`
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=10"`
}

type GetVipOrdersResp struct {
	BaseResp
	Data  []VipOrder `json:"data"`
	Total int        `json:"total"`
}

type GetVipPlanReq struct {
	PlanId string `path:"plan_id"`
}

type GetVipPlanResp struct {
	BaseResp
	Data VipPlan `json:"data"`
}

type GetVipPlansResp struct {
	BaseResp
	Data []VipPlan `json:"data"`
}

type LoginData struct {
	User  User   `json:"user"`
	Token string `json:"token"`
}

type LoginReq struct {
	Username string `json:"username,optional"`
	Email    string `json:"email,optional"`
	Password string `json:"password"`
}

type LoginResp struct {
	BaseResp
	Data LoginData `json:"data"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResp struct {
	BaseResp
	Data User `json:"data"`
}

type SyncUserVipStatusData struct {
	IsVip     bool   `json:"is_vip"`
	ExpiresAt string `json:"expires_at"`
}

type SyncUserVipStatusReq struct {
	UserId string `path:"user_id"`
}

type SyncUserVipStatusResp struct {
	BaseResp
	Data SyncUserVipStatusData `json:"data"`
}

type UpdateAIUsageReq struct {
	UserId    string `path:"user_id"`
	UsageType string `json:"usage_type"` // chat, content, analysis
}

type UpdateAIUsageResp struct {
	BaseResp
	Data AIUsageData `json:"data"`
}

type UpdateAutoRenewReq struct {
	UserId    string `path:"user_id"`
	AutoRenew bool   `json:"auto_renew"`
}

type UpdateUserInfoReq struct {
	UserId   string `path:"user_id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Avatar   string `json:"avatar"`
}

type UpdateUserInfoResp struct {
	BaseResp
	Data User `json:"data"`
}

type UpdateUserPasswordReq struct {
	UserId      string `path:"user_id"`
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type UpdateUserPasswordResp struct {
	BaseResp
}

type UpdateUserVipReq struct {
	UserId     string `path:"user_id"`
	IsVip      bool   `json:"is_vip"`
	VipExpires string `json:"vip_expires"`
}

type UpdateUserVipResp struct {
	BaseResp
	Data User `json:"data"`
}

type User struct {
	Id           string `json:"id"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	Avatar       string `json:"avatar"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
	IsVip        bool   `json:"is_vip"`
	VipExpiresAt string `json:"vip_expires_at"`
	AutoRenew    bool   `json:"auto_renew"`
}

type UserVipStatusData struct {
	IsVip     bool   `json:"is_vip"`
	ExpiresAt string `json:"expires_at"`
	AutoRenew bool   `json:"auto_renew"`
}

type VipOrder struct {
	Id        string  `json:"id"`
	UserId    string  `json:"user_id"`
	PlanId    string  `json:"plan_id"`
	PlanName  string  `json:"plan_name"`
	Amount    float64 `json:"amount"`
	Status    string  `json:"status"`
	CreatedAt string  `json:"created_at"`
	PaidAt    string  `json:"paid_at"`
}

type VipPlan struct {
	Id           string  `json:"id"`
	Name         string  `json:"name"`
	Description  string  `json:"description"`
	Price        float64 `json:"price"`
	DurationDays int     `json:"duration_days"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
}

type VipRecord struct {
	Id        string `json:"id"`
	UserId    string `json:"user_id"`
	PlanId    string `json:"plan_id"`
	PlanName  string `json:"plan_name"`
	StartAt   string `json:"start_at"`
	EndAt     string `json:"end_at"`
	Status    string `json:"status"`
	CreatedAt string `json:"created_at"`
}
