// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: superservice.proto

package super

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Super_Register_FullMethodName               = "/superservice.Super/Register"
	Super_Login_FullMethodName                  = "/superservice.Super/Login"
	Super_GetUserInfo_FullMethodName            = "/superservice.Super/GetUserInfo"
	Super_GetUser_FullMethodName                = "/superservice.Super/GetUser"
	Super_UpdateUserInfo_FullMethodName         = "/superservice.Super/UpdateUserInfo"
	Super_UpdateUserPassword_FullMethodName     = "/superservice.Super/UpdateUserPassword"
	Super_DeleteUser_FullMethodName             = "/superservice.Super/DeleteUser"
	Super_UpdateUserVip_FullMethodName          = "/superservice.Super/UpdateUserVip"
	Super_GetUsers_FullMethodName               = "/superservice.Super/GetUsers"
	Super_GetUserCount_FullMethodName           = "/superservice.Super/GetUserCount"
	Super_GetVipPlans_FullMethodName            = "/superservice.Super/GetVipPlans"
	Super_GetVipPlan_FullMethodName             = "/superservice.Super/GetVipPlan"
	Super_CreateVipPlan_FullMethodName          = "/superservice.Super/CreateVipPlan"
	Super_CreateVipOrder_FullMethodName         = "/superservice.Super/CreateVipOrder"
	Super_GetVipOrders_FullMethodName           = "/superservice.Super/GetVipOrders"
	Super_GetVipRecords_FullMethodName          = "/superservice.Super/GetVipRecords"
	Super_GetUserActiveVipRecord_FullMethodName = "/superservice.Super/GetUserActiveVipRecord"
	Super_GetUserVipStatus_FullMethodName       = "/superservice.Super/GetUserVipStatus"
	Super_CheckUserVip_FullMethodName           = "/superservice.Super/CheckUserVip"
	Super_UpdateAutoRenew_FullMethodName        = "/superservice.Super/UpdateAutoRenew"
	Super_SyncUserVipStatus_FullMethodName      = "/superservice.Super/SyncUserVipStatus"
)

// SuperClient is the client API for Super service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SuperClient interface {
	// 用户相关服务
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
	GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
	UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error)
	UpdateUserPassword(ctx context.Context, in *UpdateUserPasswordReq, opts ...grpc.CallOption) (*UpdateUserPasswordResp, error)
	DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResp, error)
	UpdateUserVip(ctx context.Context, in *UpdateUserVipReq, opts ...grpc.CallOption) (*UpdateUserVipResp, error)
	GetUsers(ctx context.Context, in *GetUsersReq, opts ...grpc.CallOption) (*GetUsersResp, error)
	GetUserCount(ctx context.Context, in *GetUserCountReq, opts ...grpc.CallOption) (*GetUserCountResp, error)
	// VIP套餐相关服务
	GetVipPlans(ctx context.Context, in *GetVipPlansReq, opts ...grpc.CallOption) (*GetVipPlansResp, error)
	GetVipPlan(ctx context.Context, in *GetVipPlanReq, opts ...grpc.CallOption) (*GetVipPlanResp, error)
	CreateVipPlan(ctx context.Context, in *CreateVipPlanReq, opts ...grpc.CallOption) (*CreateVipPlanResp, error)
	// VIP订单相关服务
	CreateVipOrder(ctx context.Context, in *CreateVipOrderReq, opts ...grpc.CallOption) (*CreateVipOrderResp, error)
	GetVipOrders(ctx context.Context, in *GetVipOrdersReq, opts ...grpc.CallOption) (*GetVipOrdersResp, error)
	// VIP记录相关服务
	GetVipRecords(ctx context.Context, in *GetVipRecordsReq, opts ...grpc.CallOption) (*GetVipRecordsResp, error)
	GetUserActiveVipRecord(ctx context.Context, in *GetUserActiveVipRecordReq, opts ...grpc.CallOption) (*GetUserActiveVipRecordResp, error)
	// VIP状态相关服务
	GetUserVipStatus(ctx context.Context, in *GetUserVipStatusReq, opts ...grpc.CallOption) (*GetUserVipStatusResp, error)
	CheckUserVip(ctx context.Context, in *CheckUserVipReq, opts ...grpc.CallOption) (*CheckUserVipResp, error)
	UpdateAutoRenew(ctx context.Context, in *UpdateAutoRenewReq, opts ...grpc.CallOption) (*UpdateAutoRenewResp, error)
	SyncUserVipStatus(ctx context.Context, in *SyncUserVipStatusReq, opts ...grpc.CallOption) (*SyncUserVipStatusResp, error)
}

type superClient struct {
	cc grpc.ClientConnInterface
}

func NewSuperClient(cc grpc.ClientConnInterface) SuperClient {
	return &superClient{cc}
}

func (c *superClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, Super_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, Super_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	out := new(GetUserInfoResp)
	err := c.cc.Invoke(ctx, Super_GetUserInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	out := new(GetUserResp)
	err := c.cc.Invoke(ctx, Super_GetUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error) {
	out := new(UpdateUserInfoResp)
	err := c.cc.Invoke(ctx, Super_UpdateUserInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) UpdateUserPassword(ctx context.Context, in *UpdateUserPasswordReq, opts ...grpc.CallOption) (*UpdateUserPasswordResp, error) {
	out := new(UpdateUserPasswordResp)
	err := c.cc.Invoke(ctx, Super_UpdateUserPassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResp, error) {
	out := new(DeleteUserResp)
	err := c.cc.Invoke(ctx, Super_DeleteUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) UpdateUserVip(ctx context.Context, in *UpdateUserVipReq, opts ...grpc.CallOption) (*UpdateUserVipResp, error) {
	out := new(UpdateUserVipResp)
	err := c.cc.Invoke(ctx, Super_UpdateUserVip_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) GetUsers(ctx context.Context, in *GetUsersReq, opts ...grpc.CallOption) (*GetUsersResp, error) {
	out := new(GetUsersResp)
	err := c.cc.Invoke(ctx, Super_GetUsers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) GetUserCount(ctx context.Context, in *GetUserCountReq, opts ...grpc.CallOption) (*GetUserCountResp, error) {
	out := new(GetUserCountResp)
	err := c.cc.Invoke(ctx, Super_GetUserCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) GetVipPlans(ctx context.Context, in *GetVipPlansReq, opts ...grpc.CallOption) (*GetVipPlansResp, error) {
	out := new(GetVipPlansResp)
	err := c.cc.Invoke(ctx, Super_GetVipPlans_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) GetVipPlan(ctx context.Context, in *GetVipPlanReq, opts ...grpc.CallOption) (*GetVipPlanResp, error) {
	out := new(GetVipPlanResp)
	err := c.cc.Invoke(ctx, Super_GetVipPlan_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) CreateVipPlan(ctx context.Context, in *CreateVipPlanReq, opts ...grpc.CallOption) (*CreateVipPlanResp, error) {
	out := new(CreateVipPlanResp)
	err := c.cc.Invoke(ctx, Super_CreateVipPlan_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) CreateVipOrder(ctx context.Context, in *CreateVipOrderReq, opts ...grpc.CallOption) (*CreateVipOrderResp, error) {
	out := new(CreateVipOrderResp)
	err := c.cc.Invoke(ctx, Super_CreateVipOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) GetVipOrders(ctx context.Context, in *GetVipOrdersReq, opts ...grpc.CallOption) (*GetVipOrdersResp, error) {
	out := new(GetVipOrdersResp)
	err := c.cc.Invoke(ctx, Super_GetVipOrders_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) GetVipRecords(ctx context.Context, in *GetVipRecordsReq, opts ...grpc.CallOption) (*GetVipRecordsResp, error) {
	out := new(GetVipRecordsResp)
	err := c.cc.Invoke(ctx, Super_GetVipRecords_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) GetUserActiveVipRecord(ctx context.Context, in *GetUserActiveVipRecordReq, opts ...grpc.CallOption) (*GetUserActiveVipRecordResp, error) {
	out := new(GetUserActiveVipRecordResp)
	err := c.cc.Invoke(ctx, Super_GetUserActiveVipRecord_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) GetUserVipStatus(ctx context.Context, in *GetUserVipStatusReq, opts ...grpc.CallOption) (*GetUserVipStatusResp, error) {
	out := new(GetUserVipStatusResp)
	err := c.cc.Invoke(ctx, Super_GetUserVipStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) CheckUserVip(ctx context.Context, in *CheckUserVipReq, opts ...grpc.CallOption) (*CheckUserVipResp, error) {
	out := new(CheckUserVipResp)
	err := c.cc.Invoke(ctx, Super_CheckUserVip_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) UpdateAutoRenew(ctx context.Context, in *UpdateAutoRenewReq, opts ...grpc.CallOption) (*UpdateAutoRenewResp, error) {
	out := new(UpdateAutoRenewResp)
	err := c.cc.Invoke(ctx, Super_UpdateAutoRenew_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superClient) SyncUserVipStatus(ctx context.Context, in *SyncUserVipStatusReq, opts ...grpc.CallOption) (*SyncUserVipStatusResp, error) {
	out := new(SyncUserVipStatusResp)
	err := c.cc.Invoke(ctx, Super_SyncUserVipStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SuperServer is the server API for Super service.
// All implementations must embed UnimplementedSuperServer
// for forward compatibility
type SuperServer interface {
	// 用户相关服务
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	Login(context.Context, *LoginReq) (*LoginResp, error)
	GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoResp, error)
	GetUser(context.Context, *GetUserReq) (*GetUserResp, error)
	UpdateUserInfo(context.Context, *UpdateUserInfoReq) (*UpdateUserInfoResp, error)
	UpdateUserPassword(context.Context, *UpdateUserPasswordReq) (*UpdateUserPasswordResp, error)
	DeleteUser(context.Context, *DeleteUserReq) (*DeleteUserResp, error)
	UpdateUserVip(context.Context, *UpdateUserVipReq) (*UpdateUserVipResp, error)
	GetUsers(context.Context, *GetUsersReq) (*GetUsersResp, error)
	GetUserCount(context.Context, *GetUserCountReq) (*GetUserCountResp, error)
	// VIP套餐相关服务
	GetVipPlans(context.Context, *GetVipPlansReq) (*GetVipPlansResp, error)
	GetVipPlan(context.Context, *GetVipPlanReq) (*GetVipPlanResp, error)
	CreateVipPlan(context.Context, *CreateVipPlanReq) (*CreateVipPlanResp, error)
	// VIP订单相关服务
	CreateVipOrder(context.Context, *CreateVipOrderReq) (*CreateVipOrderResp, error)
	GetVipOrders(context.Context, *GetVipOrdersReq) (*GetVipOrdersResp, error)
	// VIP记录相关服务
	GetVipRecords(context.Context, *GetVipRecordsReq) (*GetVipRecordsResp, error)
	GetUserActiveVipRecord(context.Context, *GetUserActiveVipRecordReq) (*GetUserActiveVipRecordResp, error)
	// VIP状态相关服务
	GetUserVipStatus(context.Context, *GetUserVipStatusReq) (*GetUserVipStatusResp, error)
	CheckUserVip(context.Context, *CheckUserVipReq) (*CheckUserVipResp, error)
	UpdateAutoRenew(context.Context, *UpdateAutoRenewReq) (*UpdateAutoRenewResp, error)
	SyncUserVipStatus(context.Context, *SyncUserVipStatusReq) (*SyncUserVipStatusResp, error)
	mustEmbedUnimplementedSuperServer()
}

// UnimplementedSuperServer must be embedded to have forward compatible implementations.
type UnimplementedSuperServer struct {
}

func (UnimplementedSuperServer) Register(context.Context, *RegisterReq) (*RegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedSuperServer) Login(context.Context, *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedSuperServer) GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedSuperServer) GetUser(context.Context, *GetUserReq) (*GetUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedSuperServer) UpdateUserInfo(context.Context, *UpdateUserInfoReq) (*UpdateUserInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserInfo not implemented")
}
func (UnimplementedSuperServer) UpdateUserPassword(context.Context, *UpdateUserPasswordReq) (*UpdateUserPasswordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserPassword not implemented")
}
func (UnimplementedSuperServer) DeleteUser(context.Context, *DeleteUserReq) (*DeleteUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedSuperServer) UpdateUserVip(context.Context, *UpdateUserVipReq) (*UpdateUserVipResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserVip not implemented")
}
func (UnimplementedSuperServer) GetUsers(context.Context, *GetUsersReq) (*GetUsersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedSuperServer) GetUserCount(context.Context, *GetUserCountReq) (*GetUserCountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserCount not implemented")
}
func (UnimplementedSuperServer) GetVipPlans(context.Context, *GetVipPlansReq) (*GetVipPlansResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVipPlans not implemented")
}
func (UnimplementedSuperServer) GetVipPlan(context.Context, *GetVipPlanReq) (*GetVipPlanResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVipPlan not implemented")
}
func (UnimplementedSuperServer) CreateVipPlan(context.Context, *CreateVipPlanReq) (*CreateVipPlanResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVipPlan not implemented")
}
func (UnimplementedSuperServer) CreateVipOrder(context.Context, *CreateVipOrderReq) (*CreateVipOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVipOrder not implemented")
}
func (UnimplementedSuperServer) GetVipOrders(context.Context, *GetVipOrdersReq) (*GetVipOrdersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVipOrders not implemented")
}
func (UnimplementedSuperServer) GetVipRecords(context.Context, *GetVipRecordsReq) (*GetVipRecordsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVipRecords not implemented")
}
func (UnimplementedSuperServer) GetUserActiveVipRecord(context.Context, *GetUserActiveVipRecordReq) (*GetUserActiveVipRecordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserActiveVipRecord not implemented")
}
func (UnimplementedSuperServer) GetUserVipStatus(context.Context, *GetUserVipStatusReq) (*GetUserVipStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserVipStatus not implemented")
}
func (UnimplementedSuperServer) CheckUserVip(context.Context, *CheckUserVipReq) (*CheckUserVipResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUserVip not implemented")
}
func (UnimplementedSuperServer) UpdateAutoRenew(context.Context, *UpdateAutoRenewReq) (*UpdateAutoRenewResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAutoRenew not implemented")
}
func (UnimplementedSuperServer) SyncUserVipStatus(context.Context, *SyncUserVipStatusReq) (*SyncUserVipStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncUserVipStatus not implemented")
}
func (UnimplementedSuperServer) mustEmbedUnimplementedSuperServer() {}

// UnsafeSuperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SuperServer will
// result in compilation errors.
type UnsafeSuperServer interface {
	mustEmbedUnimplementedSuperServer()
}

func RegisterSuperServer(s grpc.ServiceRegistrar, srv SuperServer) {
	s.RegisterService(&Super_ServiceDesc, srv)
}

func _Super_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).GetUserInfo(ctx, req.(*GetUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).GetUser(ctx, req.(*GetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_UpdateUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).UpdateUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_UpdateUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).UpdateUserInfo(ctx, req.(*UpdateUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_UpdateUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).UpdateUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_UpdateUserPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).UpdateUserPassword(ctx, req.(*UpdateUserPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).DeleteUser(ctx, req.(*DeleteUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_UpdateUserVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserVipReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).UpdateUserVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_UpdateUserVip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).UpdateUserVip(ctx, req.(*UpdateUserVipReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_GetUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).GetUsers(ctx, req.(*GetUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_GetUserCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).GetUserCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_GetUserCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).GetUserCount(ctx, req.(*GetUserCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_GetVipPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVipPlansReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).GetVipPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_GetVipPlans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).GetVipPlans(ctx, req.(*GetVipPlansReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_GetVipPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVipPlanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).GetVipPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_GetVipPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).GetVipPlan(ctx, req.(*GetVipPlanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_CreateVipPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVipPlanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).CreateVipPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_CreateVipPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).CreateVipPlan(ctx, req.(*CreateVipPlanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_CreateVipOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVipOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).CreateVipOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_CreateVipOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).CreateVipOrder(ctx, req.(*CreateVipOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_GetVipOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVipOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).GetVipOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_GetVipOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).GetVipOrders(ctx, req.(*GetVipOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_GetVipRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVipRecordsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).GetVipRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_GetVipRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).GetVipRecords(ctx, req.(*GetVipRecordsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_GetUserActiveVipRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserActiveVipRecordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).GetUserActiveVipRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_GetUserActiveVipRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).GetUserActiveVipRecord(ctx, req.(*GetUserActiveVipRecordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_GetUserVipStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserVipStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).GetUserVipStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_GetUserVipStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).GetUserVipStatus(ctx, req.(*GetUserVipStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_CheckUserVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUserVipReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).CheckUserVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_CheckUserVip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).CheckUserVip(ctx, req.(*CheckUserVipReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_UpdateAutoRenew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAutoRenewReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).UpdateAutoRenew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_UpdateAutoRenew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).UpdateAutoRenew(ctx, req.(*UpdateAutoRenewReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Super_SyncUserVipStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncUserVipStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperServer).SyncUserVipStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Super_SyncUserVipStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperServer).SyncUserVipStatus(ctx, req.(*SyncUserVipStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Super_ServiceDesc is the grpc.ServiceDesc for Super service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Super_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "superservice.Super",
	HandlerType: (*SuperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Super_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Super_Login_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _Super_GetUserInfo_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Super_GetUser_Handler,
		},
		{
			MethodName: "UpdateUserInfo",
			Handler:    _Super_UpdateUserInfo_Handler,
		},
		{
			MethodName: "UpdateUserPassword",
			Handler:    _Super_UpdateUserPassword_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Super_DeleteUser_Handler,
		},
		{
			MethodName: "UpdateUserVip",
			Handler:    _Super_UpdateUserVip_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _Super_GetUsers_Handler,
		},
		{
			MethodName: "GetUserCount",
			Handler:    _Super_GetUserCount_Handler,
		},
		{
			MethodName: "GetVipPlans",
			Handler:    _Super_GetVipPlans_Handler,
		},
		{
			MethodName: "GetVipPlan",
			Handler:    _Super_GetVipPlan_Handler,
		},
		{
			MethodName: "CreateVipPlan",
			Handler:    _Super_CreateVipPlan_Handler,
		},
		{
			MethodName: "CreateVipOrder",
			Handler:    _Super_CreateVipOrder_Handler,
		},
		{
			MethodName: "GetVipOrders",
			Handler:    _Super_GetVipOrders_Handler,
		},
		{
			MethodName: "GetVipRecords",
			Handler:    _Super_GetVipRecords_Handler,
		},
		{
			MethodName: "GetUserActiveVipRecord",
			Handler:    _Super_GetUserActiveVipRecord_Handler,
		},
		{
			MethodName: "GetUserVipStatus",
			Handler:    _Super_GetUserVipStatus_Handler,
		},
		{
			MethodName: "CheckUserVip",
			Handler:    _Super_CheckUserVip_Handler,
		},
		{
			MethodName: "UpdateAutoRenew",
			Handler:    _Super_UpdateAutoRenew_Handler,
		},
		{
			MethodName: "SyncUserVipStatus",
			Handler:    _Super_SyncUserVipStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "superservice.proto",
}
